### ISSUE TITLE
Error while downloading in Windows 10 64 bit

### ISSUE THREAD

**Issue by bsr126** [aweers/BBB-Downloader#1]
I am getting the following errors 
![Screenshot 2021-08-05 074218](https://user-images.githubusercontent.com/9985544/128280102-202806b2-4364-4c7e-9139-6b6368ff5a26.png)

**Comment by aweers** [comment]
Sorry for the delayed response:
It looks like there is a problem with your config file. Do you have a config.ini file in the same directory as described in README?

Your config file should look like this:
```
[DEFAULT] 
base_url = https://conf.calicut.nielit.in/presentation/
```

I hope this resolves the error. If not, please feel free to answer.

**Comment by bsr126** [comment]
Nope it still doesn't work. I followed everything as you said. Check the
screenshots

[image: Screenshot 2021-08-12 114308.png]

[image: Screenshot 2021-08-12 114235.png]

[image: Screenshot 2021-08-12 114149.png]

Here is the link I want to download
https://conf.calicut.nielit.in/playback/presentation/2.0/playback.html?meetingId=cdbdf357a72a822a89150469ab4760c298d5ae64-1628504710065

And I have attached the config.ini.example file as well.

**Comment by aweers** [comment]
Ok, thanks for sharing the link. I can't see your images or config.ini but was able to reproduce the error. 
I ran into the same error a while ago and fixed it with a quick-and-dirty approach. I will add the changes to this repository soon, I hope I find time tomorrow.

**Comment by aweers** [comment]
Sorry again for the long time to fix this... I am quite busy at the moment. Due to the long video and the not optimized code from me it took quite some time to test different settings. 
But I pushed a working solution for your issue: 2ee39b5. It is a quick fix and not well integrated into the other parts of the program, but it will download your video. 
If you want to beautify the code or add a feature, pull request are very welcome.

Just enter the base_url (line 25): https://conf.calicut.nielit.in/
and id (line 26): cdbdf357a72a822a89150469ab4760c298d5ae64-1628504710065
and it will work.
